# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: brewfile
        name: update brewfile
        entry: bash -c 'brew bundle dump --force'
        language: system
        types: [bash]
        always_run: true
        verbose: true
